# Generated by Django 5.0.2 on 2024-03-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirQualityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('particulate_matter', models.FloatField()),
                ('carbon_monoxide', models.FloatField()),
                ('air_quality_index', models.FloatField()),
                ('nitrogen_dioxide', models.FloatField()),
            ],
        ),
    ]
