# Generated by Django 5.0.2 on 2024-03-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_quality_app', '0002_airqualitydata_nitrogen_dioxide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airqualitydata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
